services:
  radio-web:
    build:
      context: .
      target: build
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    env_file:
      - path: .env
        required: false
    environment:
      - NODE_ENV=development
